package com.moodspaces.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.moodspaces.model.MoodSelection;
import com.moodspaces.model.MoodSpot;
import com.moodspaces.model.MoodTask;
import com.moodspaces.model.MoodPerson;
import com.moodspaces.model.MoodEntry;
import com.moodspaces.model.MoodEntryPersonMap;

import com.moodspaces.model.MoodSelectionDao;
import com.moodspaces.model.MoodSpotDao;
import com.moodspaces.model.MoodTaskDao;
import com.moodspaces.model.MoodPersonDao;
import com.moodspaces.model.MoodEntryDao;
import com.moodspaces.model.MoodEntryPersonMapDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig moodSelectionDaoConfig;
    private final DaoConfig moodSpotDaoConfig;
    private final DaoConfig moodTaskDaoConfig;
    private final DaoConfig moodPersonDaoConfig;
    private final DaoConfig moodEntryDaoConfig;
    private final DaoConfig moodEntryPersonMapDaoConfig;

    private final MoodSelectionDao moodSelectionDao;
    private final MoodSpotDao moodSpotDao;
    private final MoodTaskDao moodTaskDao;
    private final MoodPersonDao moodPersonDao;
    private final MoodEntryDao moodEntryDao;
    private final MoodEntryPersonMapDao moodEntryPersonMapDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        moodSelectionDaoConfig = daoConfigMap.get(MoodSelectionDao.class).clone();
        moodSelectionDaoConfig.initIdentityScope(type);

        moodSpotDaoConfig = daoConfigMap.get(MoodSpotDao.class).clone();
        moodSpotDaoConfig.initIdentityScope(type);

        moodTaskDaoConfig = daoConfigMap.get(MoodTaskDao.class).clone();
        moodTaskDaoConfig.initIdentityScope(type);

        moodPersonDaoConfig = daoConfigMap.get(MoodPersonDao.class).clone();
        moodPersonDaoConfig.initIdentityScope(type);

        moodEntryDaoConfig = daoConfigMap.get(MoodEntryDao.class).clone();
        moodEntryDaoConfig.initIdentityScope(type);

        moodEntryPersonMapDaoConfig = daoConfigMap.get(MoodEntryPersonMapDao.class).clone();
        moodEntryPersonMapDaoConfig.initIdentityScope(type);

        moodSelectionDao = new MoodSelectionDao(moodSelectionDaoConfig, this);
        moodSpotDao = new MoodSpotDao(moodSpotDaoConfig, this);
        moodTaskDao = new MoodTaskDao(moodTaskDaoConfig, this);
        moodPersonDao = new MoodPersonDao(moodPersonDaoConfig, this);
        moodEntryDao = new MoodEntryDao(moodEntryDaoConfig, this);
        moodEntryPersonMapDao = new MoodEntryPersonMapDao(moodEntryPersonMapDaoConfig, this);

        registerDao(MoodSelection.class, moodSelectionDao);
        registerDao(MoodSpot.class, moodSpotDao);
        registerDao(MoodTask.class, moodTaskDao);
        registerDao(MoodPerson.class, moodPersonDao);
        registerDao(MoodEntry.class, moodEntryDao);
        registerDao(MoodEntryPersonMap.class, moodEntryPersonMapDao);
    }
    
    public void clear() {
        moodSelectionDaoConfig.getIdentityScope().clear();
        moodSpotDaoConfig.getIdentityScope().clear();
        moodTaskDaoConfig.getIdentityScope().clear();
        moodPersonDaoConfig.getIdentityScope().clear();
        moodEntryDaoConfig.getIdentityScope().clear();
        moodEntryPersonMapDaoConfig.getIdentityScope().clear();
    }

    public MoodSelectionDao getMoodSelectionDao() {
        return moodSelectionDao;
    }

    public MoodSpotDao getMoodSpotDao() {
        return moodSpotDao;
    }

    public MoodTaskDao getMoodTaskDao() {
        return moodTaskDao;
    }

    public MoodPersonDao getMoodPersonDao() {
        return moodPersonDao;
    }

    public MoodEntryDao getMoodEntryDao() {
        return moodEntryDao;
    }

    public MoodEntryPersonMapDao getMoodEntryPersonMapDao() {
        return moodEntryPersonMapDao;
    }

}
